### ISSUE TITLE
touchio access

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_CircuitPlayground#8]
@kattni @tannewt I saw some draft code enabling touchio on all the A<n> pins. The code I saw may have changed since then, but I had a few comments based on that version

1. Each pin touch value has its own property name. (e.g., `touch_A2`). I have some use cases where an indexable sequence would be more convenient, but I can understand why separate property names are simpler.
2. The properties were implemented by using `__get_attr__` at runtime. This reduces the code size, but it also makes the properties invisible to `dir(cpx)` and to tab-completion. So I can't see that they exist by typing `cpx.<TAB>`. The size difference appeared to be about 600 bytes (based on `.mpy` size).
3. The `TouchIn` objects were created for all pins in `__init()__`. This claims the pins for use solely with `TouchIn`, so they can't be used for something else, like `AnalogIn` or `AnalogOut`, or `DIgitalInOut`. It might be better to create the objects on first access to `touch_A<n>`, so that the pins stay free for other uses otherwise.

**Comment by kattni** [comment]
The code hasn’t changed since that draft.

1. I agree there are use cases where an indexable sequence would be convenient, but I want the `touch` code to be the same as the labels on the board, e.g. `touch_A1`, etc.
2. The `__getattr__` function was created to try to cut down on memory usage, as we were getting so close to running out. However, as well as the tab completion issues, it also causes issues with Sphinx documentation. I didn’t realise at the time that the entire library was going to be either offered as a `.mpy` file or frozen in the firmware. This eliminates the need to include a minor memory optimisation, especially when it causes so many other issues.
3. This makes a lot of sense. We opted to do the same thing in other parts of the API. I’ll sort this out before making a pull request.

Thank you for the feedback!

**Comment by kattni** [comment]
Touch has been approved. Thank you again for your suggestions!
